import { Injectable, Injector } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { map } from 'rxjs/operators';
import { menuTypes } from 'src/app/shared/enums/menu.constant';

@Injectable()
export class RouteLoaderService {

  currentSettings: any;
  menu = '';

  constructor(
    private httpClient: HttpClient,
    private injector: Injector
  ) {

  }

  // loadSettings(): Promise<any> {
  //     return new Promise((resolve, reject) => {
  //         setTimeout(() => {
  //             const router = this.injector.get(Router);
  //             console.log(router);
  //             this.api.getMenus().then(
  //                     response => {
  //                         console.log('is Dynamic Menu available?:'+(!Array.isArray(response) || 0==response.length)? 'DM-No!':'DM-Yes!');
  //                         this.currentSettings =  response;
  //                         console.log('current settings',this.currentSettings);
  //                         resolve(true);
  //                     },
  //                     err => {
  //                         console.log(err+' and so, loading default menu');
  //                         this.currentSettings = SNCMenus;
  //                         reject(false);
  //                     }
  //                 );
  //         });
  //     });
  // }

  public GetChildMenu(currentRoute, menuType?: menuTypes) {
    this.currentSettings =  [
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 5,
          "textID": 2,
          "text": "HOME",
          "routePath": "/home",
          "imgPath": "icon-home",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": []
        },
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 5,
          "textID": 2,
          "text": "CLIENTS",
          "routePath": "/client",
          "imgPath": "icon-guest",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "ALL CLIENTS",
              "routePath": "/client/allclients",
              "imgPath": "/client/allclients",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },   
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "RECENTS",
              "routePath": "/client/recents",
              "imgPath": "/client/recents",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },  
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "VIP",
              "routePath": "/client/vip",
              "imgPath": "/client/vip",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },  
          ]
        },
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "SETTINGS",
          "routePath": "/settings",
          "imgPath": "icon-settings",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "COMMISSION SETUP",
              "routePath": "/settings/commisionsetup",
              "imgPath": "/settings/commisionsetup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },        
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "RETAIL SETUP",
              "routePath": "/settings/retailsetup",
              "imgPath": "/settings/retailsetup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Code Setup",
                  "routePath": "/settings/retailsetup/codesetup",
                  "imgPath": "/settings/retailsetup/codesetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": [
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Credit Card Terminals",
                      "routePath": "/settings/retailsetup/codesetup/creditcardterminals",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Outlets",
                      "routePath": "/settings/retailsetup/codesetup/outlets",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Category Groups",
                      "routePath": "/settings/retailsetup/codesetup/categorygroups",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Retail Categories",
                      "routePath": "/settings/retailsetup/codesetup/retailcategories",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Retail Sub Categories",
                      "routePath": "/settings/retailsetup/codesetup/retailsubcategories",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Unit of Measure",
                      "routePath": "/settings/retailsetup/codesetup/unitofmeasure",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Taxes",
                      "routePath": "/settings/retailsetup/codesetup/taxes",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Discount Types",
                      "routePath": "/settings/retailsetup/codesetup/discounttypes",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Payment Methods",
                      "routePath": "/settings/retailsetup/codesetup/paymentmethods",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Quick Sale Categories",
                      "routePath": "/settings/retailsetup/codesetup/quicksalecategories",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "VAT Configuration",
                      "routePath": "/settings/retailsetup/codesetup/vatconfiguration",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Retail Feature Configuration",
                      "routePath": "/settings/retailsetup/codesetup/retailfeatureconfiguration",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Credit Cards",
                      "routePath": "/settings/retailsetup/codesetup/creditcards",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Gift Cards",
                      "routePath": "/settings/retailsetup/codesetup/giftcards",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 5,
                      "textID": 2,
                      "text": "Vendor Types",
                      "routePath": "/settings/retailsetup/codesetup/vendortypes",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    }
                  ]
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Retail Setup",
                  "routePath": "/settings/retailsetup/retailsetup",
                  "imgPath": "/settings/retailsetup/retailsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Quick Sale Setup",
                  "routePath": "/settings/retailsetup/quicksalesetup",
                  "imgPath": "/settings/retailsetup/quicksalesetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Commission Setup",
                  "routePath": "/settings/retailsetup/commissionsetup",
                  "imgPath": "/settings/retailsetup/commissionsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Discount Configuration",
                  "routePath": "/settings/retailsetup/discountconfiguration",
                  "imgPath": "/settings/retailsetup/discountconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Category Linking",
                  "routePath": "/settings/retailsetup/categorylinking",
                  "imgPath": "/settings/retailsetup/categorylinking",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Vendor Setup",
                  "routePath": "/settings/retailsetup/vendorsetup",
                  "imgPath": "/settings/retailsetup/vendorsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                }
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "INVENTORY",
              "routePath": "/settings/inventorysetup",
              "imgPath": "/settings/inventorysetup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "UTILITIES",
              "routePath": "/settings/utilities",
              "imgPath": "/settings/utilities",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Receipt Configuration",
                  "routePath": "/settings/utilities/receiptconfiguration",
                  "imgPath": "/settings/utilities/receiptconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "User Machine Configuration",
                  "routePath": "/settings/utilities/usermachineconfiguration",
                  "imgPath": "/settings/utilities/usermachineconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Templates",
                  "routePath": "/settings/utilities/templates",
                  "imgPath": "/settings/utilities/templates",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": [
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Email Templates",
                      "routePath": "/settings/utilities/templates/email",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "SMS Templates",
                      "routePath": "/settings/utilities/templates/sms",
                      "imgPath": "",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                  ]
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Distribution List",
                  "routePath": "/settings/utilities/distributionlist",
                  "imgPath": "/settings/utilities/distributionlist",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                }
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "User Setup",
              "routePath": "/settings/usersetup",
              "imgPath": "",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "User Setup",
                  "routePath": "/settings/usersetup/usersetup",
                  "imgPath": "",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Role Setup",
                  "routePath": "/settings/usersetup/rolesetup",
                  "imgPath": "",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "User Role Configuration",
                  "routePath": "/settings/usersetup/userroleconfiguration",
                  "imgPath": "",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": [
                  ]
                }
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "SYSTEM SETUP",
              "routePath": "/settings/systemsetup",
              "imgPath": "/settings/systemsetup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Property Information",
                  "routePath": "/settings/systemsetup/propertyinfo",
                  "imgPath": "",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Miscellaneous",
                  "routePath": "/settings/systemsetup/miscellaneous",
                  "imgPath": "",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Notifications",
                  "routePath": "/settings/systemsetup/notifications",
                  "imgPath": "",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                }
              ]
            }
          ]
        },
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 5,
          "textID": 2,
          "text": "SHOP",
          "routePath": "/shop/viewshop",
          "imgPath": "icon-shop",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "RETAIL ITEMS",
              "routePath": "/shop/viewshop/retailitems",
              "imgPath": "/shop/viewshop/retailitems",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "RETAIL TRANSACTIONS",
              "routePath": "/shop/viewshop/retailtransactions",
              "imgPath": "/shop/viewshop/retailtransactions",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Open Transactions",
                  "routePath": "/shop/viewshop/retailtransactions/opentransactions",
                  "imgPath": "/shop/viewshop/retailtransactions/opentransactions",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Correct/Void",
                  "routePath": "/shop/viewshop/retailtransactions/correctvoid",
                  "imgPath": "/shop/viewshop/retailtransactions/correctvoid",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Return with Ticket",
                  "routePath": "/shop/viewshop/retailtransactions/returnwithticket",
                  "imgPath": "/shop/viewshop/retailtransactions/returnwithticket",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Return without Ticket",
                  "routePath": "/shop/viewshop/retailtransactions/returnwithoutticket",
                  "imgPath": "/shop/viewshop/retailtransactions/returnwithoutticket",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Modify Posted Commissions",
                  "routePath": "/shop/viewshop/retailtransactions/modifypostedcommission",
                  "imgPath": "/shop/viewshop/retailtransactions/modifypostedcommission",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 5,
                  "textID": 2,
                  "text": "Reprint Ticket",
                  "routePath": "/shop/viewshop/retailtransactions/reprintticket",
                  "imgPath": "/shop/viewshop/retailtransactions/reprintticket",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "GIFT CARDS",
              "routePath": "/shop/viewshop/giftcards",
              "imgPath": "/shop/viewshop/giftcards",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 5,
          "textID": 2,
          "text": "REPORTS",
          "routePath": "/reports",
          "imgPath": "icon-reports",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 5,
              "textID": 2,
              "text": "RETAIL",
              "routePath": "/reports/retail",
              "imgPath": "/reports/retail",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "AUDIT",
          "routePath": "/audit",
          "imgPath": "icon-Audit",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "DAY END",
              "routePath": "/audit/dayend",
              "imgPath": "/audit/dayend",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },
      ]
    };
    const menuList = this.currentSettings;

    if (menuList) {
      if (currentRoute === '/') {
        return menuList;
      }
      // let currentMenu = menuList.menu.find(x => x.route === currentRoute);
      let currentMenu = menuList.find(x => x.routePath === currentRoute);
      if (currentMenu) {
        return currentMenu;
      } else {
        for (const x of menuList) {
          const obj: any[] = x.linkedElement ? x.linkedElement : null;
          // currentMenu = obj && obj.find(sub => sub.route === currentRoute);
          currentMenu = obj && obj.find(sub => sub.routePath === currentRoute);
          if (currentMenu) {
            return currentMenu;
          }
          if (menuType === menuTypes.lowerLevel && obj) {
            for (const childMenu of obj) {
              const childObj: any[] = childMenu.linkedElement ? childMenu.linkedElement : null;
              // const currentChildMenu = childObj && childObj.find(sub => sub.route === currentRoute);
              const currentChildMenu = childObj && childObj.find(sub => sub.routePath === currentRoute);
              if (currentChildMenu) {
                return currentChildMenu;
              }

            }
          }
        }
      }
    }

  }
}
