import { Injectable, Injector } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { map } from 'rxjs/operators';
import { menuTypes } from 'src/app/shared/enums/menu.constant';

@Injectable()
export class RouteLoaderService {

  currentSettings: any;
  menu = '';

  constructor(
    private httpClient: HttpClient,
    private injector: Injector
  ) {

  }

  // loadSettings(): Promise<any> {
  //     return new Promise((resolve, reject) => {
  //         setTimeout(() => {
  //             const router = this.injector.get(Router);
  //             console.log(router);
  //             this.api.getMenus().then(
  //                     response => {
  //                         console.log('is Dynamic Menu available?:'+(!Array.isArray(response) || 0==response.length)? 'DM-No!':'DM-Yes!');
  //                         this.currentSettings =  response;
  //                         console.log('current settings',this.currentSettings);
  //                         resolve(true);
  //                     },
  //                     err => {
  //                         console.log(err+' and so, loading default menu');
  //                         this.currentSettings = SNCMenus;
  //                         reject(false);
  //                     }
  //                 );
  //         });
  //     });
  // }

  public GetChildMenu(currentRoute, menuType?: menuTypes) {
    this.currentSettings = {
      "result": [
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "SETTINGS",
          "routePath": "/setting",
          "imgPath": "/setting",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "SETUP",
              "routePath": "/setting/setup",
              "imgPath": "/setting/setup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Service Group",
                  "routePath": "/setting/setup/servicegroup",
                  "imgPath": "/setting/setup/servicegroup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Service Location",
                  "routePath": "/setting/setup/servicelocation",
                  "imgPath": "/setting/setup/servicelocation",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Therapist Setup",
                  "routePath": "/setting/setup/therapistsetup",
                  "imgPath": "/setting/setup/therapistsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Medical Condition",
                  "routePath": "/setting/setup/medicalcondition",
                  "imgPath": "/setting/setup/medicalcondition",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Service Add On",
                  "routePath": "/setting/setup/serviceaddon",
                  "imgPath": "/setting/setup/serviceaddon",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Service Equipment",
                  "routePath": "/setting/setup/serviceequipment",
                  "imgPath": "/setting/setup/serviceequipment",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Spa Service",
                  "routePath": "/setting/setup/spaservice",
                  "imgPath": "/setting/setup/spaservice",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Spa Package",
                  "routePath": "/setting/setup/spapackage",
                  "imgPath": "/setting/setup/spapackage",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Cancel Reason",
                  "routePath": "/setting/setup/cancelreason",
                  "imgPath": "/setting/setup/cancelreason",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Package Classes",
                  "routePath": "/setting/setup/packageclasses",
                  "imgPath": "/setting/setup/packageclasses",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Lunch Setup",
                  "routePath": "/setting/setup/lunchsetup",
                  "imgPath": "/setting/setup/lunchsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Color Linking",
                  "routePath": "/setting/setup/colorlinking",
                  "imgPath": "/setting/setup/colorlinking",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Break Type",
                  "routePath": "/setting/setup/breaktype",
                  "imgPath": "/setting/setup/breaktype",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Price Type",
                  "routePath": "/setting/setup/pricetype",
                  "imgPath": "/setting/setup/pricetype",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Custom Fields",
                  "routePath": "/setting/setup/customfields",
                  "imgPath": "/setting/setup/customfields",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "STAFF SCHEDULE",
              "routePath": "/setting/staffSchedule",
              "imgPath": "/setting/staffSchedule",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "COMMISSION SETUP",
              "routePath": "/setting/commissionsetup",
              "imgPath": "/setting/commissionsetup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "PACKAGE YIELDING",
              "routePath": "/setting/packageyielding",
              "imgPath": "/setting/packageyielding",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "SERVICE YIELDING",
              "routePath": "/setting/serviceyielding",
              "imgPath": "/setting/serviceyielding",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "UTILITIES",
              "routePath": "/setting/utilities",
              "imgPath": "/setting/utilities",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Equipment Maintenance",
                  "routePath": "/setting/utilities/equipmentmaintenance",
                  "imgPath": "/setting/utilities/equipmentmaintenance",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Location Maintenance",
                  "routePath": "/setting/utilities/locationmaintenance",
                  "imgPath": "/setting/utilities/locationmaintenance",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Therapist Unavailability",
                  "routePath": "/setting/utilities/therapistunavailability",
                  "imgPath": "/setting/utilities/therapistunavailability",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Move Multiple Appointments",
                  "routePath": "/setting/utilities/movemultipleappointments",
                  "imgPath": "/setting/utilities/movemultipleappointments",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Receipt Configuration",
                  "routePath": "/setting/utilities/receiptconfiguration",
                  "imgPath": "/setting/utilities/receiptconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "User/Machine Configuration",
                  "routePath": "/setting/utilities/usermachineconfiguration",
                  "imgPath": "/setting/utilities/usermachineconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Templates",
                  "routePath": "/setting/utilities/templates",
                  "imgPath": "/setting/utilities/templates",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": [
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Email Templates",
                      "routePath": "/setting/utilities/templates/email",
                      "imgPath": "/setting/utilities/templates/email",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "SMS Templates",
                      "routePath": "/setting/utilities/templates/sms",
                      "imgPath": "/setting/utilities/templates/sms",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                  ]
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Distribution List",
                  "routePath": "/setting/utilities/distributionlist",
                  "imgPath": "/setting/utilities/distributionlist",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                }
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "RETAIL SETUP",
              "routePath": "/setting/retailsetup",
              "imgPath": "/setting/retailsetup",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Code Setup",
                  "routePath": "/setting/retailsetup/codesetup",
                  "imgPath": "/setting/retailsetup/codesetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": [
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Credit Card Terminals",
                      "routePath": "/setting/retailsetup/codesetup/creditcardterminals",
                      "imgPath": "/setting/retailsetup/codesetup/creditcardterminals",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Outlets",
                      "routePath": "/setting/retailsetup/codesetup/outlets",
                      "imgPath": "/setting/retailsetup/codesetup/outlets",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Category Groups",
                      "routePath": "/setting/retailsetup/codesetup/categorygroups",
                      "imgPath": "/setting/retailsetup/codesetup/categorygroups",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Retail Categories",
                      "routePath": "/setting/retailsetup/codesetup/retailcategories",
                      "imgPath": "/setting/retailsetup/codesetup/retailcategories",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Retail Sub Categories",
                      "routePath": "/setting/retailsetup/codesetup/retailsubcategories",
                      "imgPath": "/setting/retailsetup/codesetup/retailsubcategories",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Unit of Measure",
                      "routePath": "/setting/retailsetup/codesetup/unitofmeasure",
                      "imgPath": "/setting/retailsetup/codesetup/unitofmeasure",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Taxes",
                      "routePath": "/setting/retailsetup/codesetup/taxes",
                      "imgPath": "/setting/retailsetup/codesetup/taxes",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Discount Types",
                      "routePath": "/setting/retailsetup/codesetup/discounttypes",
                      "imgPath": "/setting/retailsetup/codesetup/discounttypes",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Payment Methods",
                      "routePath": "/setting/retailsetup/codesetup/paymentmethods",
                      "imgPath": "/setting/retailsetup/codesetup/paymentmethods",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Quick Sale Categories",
                      "routePath": "/setting/retailsetup/codesetup/quicksalecategories",
                      "imgPath": "/setting/retailsetup/codesetup/quicksalecategories",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "VAT Configuration",
                      "routePath": "/setting/retailsetup/codesetup/vatconfiguration",
                      "imgPath": "/setting/retailsetup/codesetup/vatconfiguration",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Retail Feature Configuration",
                      "routePath": "/setting/retailsetup/codesetup/retailfeatureconfiguration",
                      "imgPath": "/setting/retailsetup/codesetup/retailfeatureconfiguration",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Credit Cards",
                      "routePath": "/setting/retailsetup/codesetup/creditcards",
                      "imgPath": "/setting/retailsetup/codesetup/creditcards",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    },
                    {
                      "elementID": 8,
                      "tenantID": 0,
                      "propertyID": 0,
                      "productID": 0,
                      "textID": 2,
                      "text": "Gift Cards",
                      "routePath": "/setting/retailsetup/codesetup/giftcards",
                      "imgPath": "/setting/retailsetup/codesetup/giftcards",
                      "order": 1,
                      "visibility": true,
                      "disable": false,
                      "parentID": 7,
                      "menuPosition": "Ternary",
                      "menuAlignment": "Vertical",
                      "externalLink": false,
                      "linkedElement": []
                    }
                  ]
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Retail Setup",
                  "routePath": "/setting/retailsetup/retailsetup",
                  "imgPath": "/setting/retailsetup/retailsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Scheduled Markdown",
                  "routePath": "/setting/retailsetup/scheduledmarkdown",
                  "imgPath": "/setting/retailsetup/scheduledmarkdown",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Quick Sale Setup",
                  "routePath": "/setting/retailsetup/quicksalesetup",
                  "imgPath": "/setting/retailsetup/quicksalesetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Commission Setup",
                  "routePath": "/setting/retailsetup/commissionsetup",
                  "imgPath": "/setting/retailsetup/commissionsetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Discount Configuration",
                  "routePath": "/setting/retailsetup/discountconfiguration",
                  "imgPath": "/setting/retailsetup/discountconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Category Linking",
                  "routePath": "/setting/retailsetup/categorylinking",
                  "imgPath": "/setting/retailsetup/categorylinking",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                }
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "INVENTORY",
              "routePath": "/setting/inventory",
              "imgPath": "/setting/inventory",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "SYSTEM CONFIG",
              "routePath": "/setting/systemconfig",
              "imgPath": "/setting/systemconfig",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Property Information",
                  "routePath": "/setting/systemconfig/propertyinformation",
                  "imgPath": "/setting/systemconfig/propertyinformation",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Appointment",
                  "routePath": "/setting/systemconfig/appointment",
                  "imgPath": "/setting/systemconfig/appointment",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Miscellaneous",
                  "routePath": "/setting/systemconfig/miscellaneous",
                  "imgPath": "/setting/systemconfig/miscellaneous",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Credit Cards",
                  "routePath": "/setting/systemconfig/creditcards",
                  "imgPath": "/setting/systemconfig/creditcards",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "rGuest Book Setup",
                  "routePath": "/setting/systemconfig/rguestbooksetup",
                  "imgPath": "/setting/systemconfig/rguestbooksetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },

                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Vat Configurations",
                  "routePath": "/setting/systemconfig/vatconfigurations",
                  "imgPath": "/setting/systemconfig/vatconfigurations",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Gift Configurations",
                  "routePath": "/setting/systemconfig/giftconfigurations",
                  "imgPath": "/setting/systemconfig/giftconfigurations",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Payement Configurations",
                  "routePath": "/setting/systemconfig/paymentconfigurations",
                  "imgPath": "/setting/systemconfig/paymentconfigurations",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Notify Configurations",
                  "routePath": "/setting/systemconfig/notifyconfigurations",
                  "imgPath": "/setting/systemconfig/notifyconfigurations",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Notifications",
                  "routePath": "/setting/systemconfig/notifications",
                  "imgPath": "/setting/systemconfig/notifications",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                }
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "USER CONFIG",
              "routePath": "/setting/userconfig",
              "imgPath": "/setting/userconfig",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "User Setup",
                  "routePath": "/setting/userconfig/usersetup",
                  "imgPath": "/setting/userconfig/usersetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Role Setup",
                  "routePath": "/setting/userconfig/rolesetup",
                  "imgPath": "/setting/userconfig/rolesetup",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "User Role Configuration",
                  "routePath": "/setting/userconfig/userroleconfiguration",
                  "imgPath": "/setting/userconfig/userroleconfiguration",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
              ]
            }
          ]
        },

        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "CLIENT",
          "routePath": "/client",
          "imgPath": "/client",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "ALL CLIENTS",
              "routePath": "/client/allclients",
              "imgPath": "/client/allclients",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "RECENTS",
              "routePath": "/client/recents",
              "imgPath": "/client/recents",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "VIP",
              "routePath": "/client/vip",
              "imgPath": "/client/vip",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },


        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "REPORTS",
          "routePath": "/report",
          "imgPath": "/report",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "APPOINTMENT",
              "routePath": "/report/appointment",
              "imgPath": "/report/appointment",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "RETAIL",
              "routePath": "/report/retail",
              "imgPath": "/report/retail",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "CLIENT",
              "routePath": "/report/client",
              "imgPath": "/report/client",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "COMMISSION/GRATUITY/SERVICE CHARGE",
              "routePath": "/report/commission",
              "imgPath": "/report/commission",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "TRANSACTION LOG",
              "routePath": "/report/transcationlog",
              "imgPath": "/report/transcationlog",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "GIFT CARDS",
              "routePath": "/report/giftcards",
              "imgPath": "/report/giftcards",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },

        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "AUDIT",
          "routePath": "/audit",
          "imgPath": "/audit",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "DAY END",
              "routePath": "/audit/dayend",
              "imgPath": "/audit/dayend",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },

        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "APPOINTMENT",
          "routePath": "/appointment",
          "imgPath": "/appointment",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "BOOK APPOINTMENT",
              "routePath": "/appointment/bookappointment",
              "imgPath": "/appointment/bookappointment",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "APPOINTMENT SEARCH",
              "routePath": "/appointment/appointmentsearch",
              "imgPath": "/appointment/appointmentsearch",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "APPOINTMENT CONFIRMATION",
              "routePath": "/appointment/appointmentconfirmation",
              "imgPath": "/appointment/appointmentconfirmation",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "WAITLIST",
              "routePath": "/appointment/waitlist",
              "imgPath": "/appointment/waitlist",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        },
        {
          "elementID": 7,
          "tenantID": 0,
          "propertyID": 0,
          "productID": 0,
          "textID": 2,
          "text": "SHOP",
          "routePath": "/shop/viewshop",
          "imgPath": "/shop/viewshop",
          "order": 2,
          "visibility": true,
          "disable": false,
          "parentID": 0,
          "menuPosition": "Primary",
          "menuAlignment": "Horizontal",
          "externalLink": false,
          "linkedElement": [
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "RETAIL ITEMS",
              "routePath": "/shop/viewshop/retailitems",
              "imgPath": "/shop/viewshop/retailitems",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "RETAIL TRANSACTIONS",
              "routePath": "/shop/viewshop/retailtransactions",
              "imgPath": "/shop/viewshop/retailtransactions",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": [
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Open Transactions",
                  "routePath": "/shop/viewshop/retailtransactions/opentransactions",
                  "imgPath": "/shop/viewshop/retailtransactions/opentransactions",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Correct/Void",
                  "routePath": "/shop/viewshop/retailtransactions/correctvoid",
                  "imgPath": "/shop/viewshop/retailtransactions/correctvoid",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Return with Ticket",
                  "routePath": "/shop/viewshop/retailtransactions/returnwithticket",
                  "imgPath": "/shop/viewshop/retailtransactions/returnwithticket",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Return without Ticket",
                  "routePath": "/shop/viewshop/retailtransactions/returnwithoutticket",
                  "imgPath": "/shop/viewshop/retailtransactions/returnwithoutticket",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Modify Posted Commissions",
                  "routePath": "/shop/viewshop/retailtransactions/modifypostedcommission",
                  "imgPath": "/shop/viewshop/retailtransactions/modifypostedcommission",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
                {
                  "elementID": 8,
                  "tenantID": 0,
                  "propertyID": 0,
                  "productID": 0,
                  "textID": 2,
                  "text": "Reprint Ticket",
                  "routePath": "/shop/viewshop/retailtransactions/reprintticket",
                  "imgPath": "/shop/viewshop/retailtransactions/reprintticket",
                  "order": 1,
                  "visibility": true,
                  "disable": false,
                  "parentID": 7,
                  "menuPosition": "Ternary",
                  "menuAlignment": "Vertical",
                  "externalLink": false,
                  "linkedElement": []
                },
              ]
            },
            {
              "elementID": 8,
              "tenantID": 0,
              "propertyID": 0,
              "productID": 0,
              "textID": 2,
              "text": "GIFT CARDS",
              "routePath": "/shop/viewshop/giftcards",
              "imgPath": "/shop/viewshop/giftcards",
              "order": 1,
              "visibility": true,
              "disable": false,
              "parentID": 7,
              "menuPosition": "secondary",
              "menuAlignment": "Horizontal",
              "externalLink": false,
              "linkedElement": []
            }
          ]
        }
      ]
    };
    const menuList = this.currentSettings.result;

    if (menuList) {
      if (currentRoute === '/') {
        return menuList;
      }
      // let currentMenu = menuList.menu.find(x => x.route === currentRoute);
      let currentMenu = menuList.find(x => x.routePath === currentRoute);
      if (currentMenu) {
        return currentMenu;
      } else {
        for (const x of menuList) {
          const obj: any[] = x.linkedElement ? x.linkedElement : null;
          // currentMenu = obj && obj.find(sub => sub.route === currentRoute);
          currentMenu = obj && obj.find(sub => sub.routePath === currentRoute);
          if (currentMenu) {
            return currentMenu;
          }
          if (menuType === menuTypes.lowerLevel && obj) {
            for (const childMenu of obj) {
              const childObj: any[] = childMenu.linkedElement ? childMenu.linkedElement : null;
              // const currentChildMenu = childObj && childObj.find(sub => sub.route === currentRoute);
              const currentChildMenu = childObj && childObj.find(sub => sub.routePath === currentRoute);
              if (currentChildMenu) {
                return currentChildMenu;
              }

            }
          }
        }
      }
    }

  }
}
